version: "3.7"

# 申明同一个网络
networks:
  net:
    name: net

# 游戏数据卷
volumes:
  consuldata:
    name: consuldata
  mqttdata:
    name: mqttdata
  redisdata:
    name: redisdata
  mongodata:
    name: mongodata
  nginxdata:
    name: nginxdata

# 服务
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - "6379:6379"
    networks:
      net:
        # 给网络取别名,可以用redis和cache找到
        aliases:
          - cache
    command: /etc/redis/redis.conf
    volumes:
      # 持久存储redis的数据
      - redisdata:/data
      # 挂载本地配置文件
      - ./redis.conf:/etc/redis/redis.conf
      # 时间同步
      # - /etc/localtime:/etc/localtime
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
    - "27017:27017"
    networks:
      net:
        # 给网络取别名,可以用mongodb和db找到
        aliases:
          - db
    command: ["mongod", "-f", "/etc/mongo/mongod.conf"]
    volumes:
      # 持久存储mongodb的数据
      - mongodata:/data/db:rw
      - mongodata:/data/configdb:rw
      # 挂载本地配置文件
      - ./mongod.conf:/etc/mongo/mongod.conf:rw
  consul:
    image: consul:latest
    container_name: consul
    ports:
    - "8500:8500"
    command: consul agent -server -bootstrap -data-dir /consul/data -node=ylconsul -bind=0.0.0.0 -config-dir=/consul/config/ -client=0.0.0.0 -ui
    networks:
      net:
        # 给网络取别名,可以用consul和discovery找到
        aliases:
          - discovery
    volumes:
      - consuldata:/consul/data    
  nats:
    image: nats:latest
    container_name: nats
    ports:
    - "4222:4222"
    - "6222:6222"
    - "8222:8222"
    command: "-c /etc/nats/nats.conf"
    networks:
      net:
        aliases:
          - nats
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:rw
  mqtt:
    image: emqx/emqx
    container_name: mqtt
    volumes:
      - mqttdata:/opt/emqx/data
      # 挂载本地配置文件
      - ./emqx.conf:/etc/emqx.conf:rw
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8084:8084"
      - "8883:8883"
      - "8083:8083"
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/:rw
      - nginxdata/:/var/cache/nginx
      - nginxdata/:/run
    networks:
      - net
    ports:
      - 10000-10100:10000-10100
      # - 80:80
      # - 443:443
    depends_on:
      - nats
      - consul
      - mongo
      - redis