version: '3.7'

# 申明同一个网络
networks:
  net:
    name: net

# 游戏数据卷
volumes:
  consuldata:
    name: consuldata
  redisdata:
    name: redisdata
  mongodata:
    name: mongodata
  nginxdata:
    name: nginxdata
# 服务
services:
  redis:
    image: redis:latest
    container_name: redis
    # ports:
    #   - '6379:6379'
    networks:
      net:
        # 给网络取别名,可以用redis和cache找到
        aliases:
          - cache
    command: /etc/redis/redis.conf
    volumes:
      # 持久存储redis的数据
      - redisdata:/data
      # 挂载本地配置文件
      - ./redis.conf:/etc/redis/redis.conf
      # 时间同步
      # - /etc/localtime:/etc/localtime
  consul:
    image: consul:latest
    container_name: consul
    # ports:
    #   - '8500:8500'
    command: consul agent -server -bootstrap -data-dir /consul/data -node=ylconsul -bind=0.0.0.0 -config-dir=/consul/config/ -client=0.0.0.0 -ui
    networks:
      net:
        # 给网络取别名,可以用consul和discovery找到
        aliases:
          - discovery
    volumes:
      - consuldata:/consul/data
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos-log/:/home/nacos/logs
      - ./custom.properties:/home/nacos/init.d/custom.properties
    networks:
      net:
        aliases:
          - nacos
    # ports:
    # - "8848:8848"
    # - "9848:9848"
  nats:
    image: nats:latest
    container_name: nats
    # ports:
    #   - '4222:4222'
    #   - '6222:6222'
    #   - '8222:8222'
    command: '-c /etc/nats/nats.conf'
    networks:
      net:
        aliases:
          - nats
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:rw
  mongo:
    image: mongo:latest
    container_name: mongo
    # ports:
    #   - '27017:27017'
    networks:
      net:
        # 给网络取别名,可以用mongodb和db找到
        aliases:
          - db
    command: ['mongod', '-f', '/etc/mongo/mongod.conf']
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: liwei1dao
    #   MONGO_INITDB_ROOT_PASSWORD: li13451234
    volumes:
      # 持久存储mongodb的数据
      - mongodata:/data/db:rw
      - mongodata:/data/configdb:rw
      # 挂载本地配置文件
      - ./mongod.conf:/etc/mongo/mongod.conf:rw
  canal:
    image: canal/canal-server:latest
    container_name: canal
    ports:
      - "11111:11111"
    networks:
      - net
    environment: 
      - canal.instance.mysql.slaveId=12
      - canal.auto.scan=false
      - canal.destinations=example
      - canal.instance.master.address=172.20.27.125:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=Idss@sjzt2021
      - canal.mq.topic=example
      - canal.instance.filter.regex=esen_approval.apt_approval
    volumes:
      # - ./example/:/home/admin/canal-server/conf/example/
      - ./canal-server/conf/:/admin/canal-server/conf/
      - ./canal-log/:/home/admin/canal-server/logs/
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-log/:/var/log/nginx/:rw
      - nginxdata/:/var/cache/nginx
      - nginxdata/:/run
    networks:
      - net
    ports:
      - 10000-10100:10000-10100
    depends_on:
      - redis
      - mongo
      - consul
      - nats
      - nacos
